spring.application.name=01_spring

# server port
server.port=8888


#ViewResolver - 템플릿 엔진을 통해서 뷰를 만들어 응답해주는 객체
# JSP 파일이 위치한 보안 구역 폴더 지정
spring.mvc.view.prefix=/WEB-INF/views/

# 확장자 지정 (JSP를 쓰실 경우)
spring.mvc.view.suffix=.jsp