spring.application.name=bowling
server.port=8282
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=C##JOELL
spring.datasource.password=JOELL

spring.mvc.view.prefix=/WEB-INF/views/member/
spring.mvc.view.suffix=.jsp


mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true